const SUBMIT_ACTION = 'SUBMIT_ACTION';

const NEW_GENRE_OPTION = 'NEW_GENRE_OPTION';
const NEW_TYPE_OPTION = 'NEW_TYPE_OPTION';
const NEW_SUBTYPE_OPTION = 'NEW_SUBTYPE_OPTION';
const NEW_TAG_OPTION = 'NEW_TAG_OPTION';
const NEW_MOOD_OPTION = 'NEW_MOOD_OPTION';
const NEW_RARITY_OPTION = 'NEW_RARYITY_OPTION';

export {
  SUBMIT_ACTION,
  NEW_GENRE_OPTION,
  NEW_TYPE_OPTION,
  NEW_SUBTYPE_OPTION,
  NEW_TAG_OPTION,
  NEW_MOOD_OPTION,
  NEW_RARITY_OPTION,
};
